### ISSUE TITLE
Can't import initial file

### ISSUE THREAD

**Issue by cchansk** [mpars0ns/scansio-sonar-es#3]
whenever i run the command to import, i am getting this error. I'm not quite sure why. Also, is there a way to import once the file is downloaded instead of running sonar_ssl.py again, which causes it to redownload?

WARNING sonar_ssl:main():188 2016-04-26 17:44:43,756| Importing 20131030-20150518_certs.gz at 2016-04-26 17:44:43.756377
WARNING sonar_ssl:main():188 2016-04-26 17:44:43,756| Importing 20131030-20150518_certs.gz at 2016-04-26 17:44:43.756377
WARNING sonar_ssl:parse_certs_file():85 2016-04-26 17:44:43,757| Opening file 20131030-20150518_certs.gz at 2016-04-26 17:44:43.757147
WARNING sonar_ssl:parse_certs_file():85 2016-04-26 17:44:43,757| Opening file 20131030-20150518_certs.gz at 2016-04-26 17:44:43.757147
Traceback (most recent call last):
  File "sonar_ssl.py", line 302, in <module>
    main(sys.argv)
  File "sonar_ssl.py", line 189, in main
    parse_certs_file(certfile, process_certs_queue)
  File "sonar_ssl.py", line 90, in parse_certs_file
    raw_cert['time'] = datetime.strptime(filedate, "%Y%m%d")
TypeError: must be string, not None

**Comment by mpars0ns** [comment]
@cchansk Thanks. I just pushed an update to the main branch  can you do a git pull and try again?

**Comment by cchansk** [comment]
Awesome. Trying it now.

**Comment by cchansk** [comment]
Working now! Thanks.

**Comment by mpars0ns** [comment]
Awesome thanks @cchansk let me know how it is going after you get moving along.
